### ISSUE TITLE
Question about print-object and dynamic-mixins

### ISSUE THREAD

**Issue by elliottjohnson** [rpav/dynamic-mixins#1]
In using dynamic-mixins I found that my PRINT-OBJECT methods were not being called for a mixed in class. 

In the case of some of my code, I would like to define PRINT-OBJECT for a parent class that will be "mixed" in with other classes.  The outcome of this is that the resulting object inherits from the MIXIN-OBJECT class, which in turn has a more specific PRINT-OBJECT method defined, which is used rather than the parent object's method.

How do you recommend I deal with such a situation?  

If I redefine PRINT-OBJECT for MIXIN-OBJECT that would change for all MIXIN-OBJECTS, which is not really an option since it would affect other packages using dynamic-mixins.  

It would appear that if there was not a specialized method for PRINT-OBJECT on MIXIN-OBJECT it would allow for the mixed-in classes to fall back to the next closest defined method, which could be one of the parent classes defined by the "user".

What are your thoughts on this?  Any alternatives that I've not considered?

Here's some trivial example code if that helps to demonstrate the issue:

    (in-package :cl)
    (defpackage :dynamix
      (:use :cl :dynamic-mixins))
    (in-package :dynamix)

    (defclass biker ()
        ((rockin :accessor rockin :initarg :rockin :initform nil)))
    (defmethod print-object ((b biker) stream)
      (print-unreadable-object (b stream :type t :identity t)
        (if (rockin b)
          (format stream "is rocking ~A!" (rockin b))
          (format stream "needs to rock a little harder!"))))
    (defclass music-mixin ()
      ()
      (:default-initargs :rockin "hard"))
    (defmethod join-band ((biker biker))
      (ensure-mix biker 'music-mixin))
    (defclass biker-listening-to-music (biker music-mixin)
      ())
    (defun print-object-test ()
      (let ((biker (make-instance 'biker))
            (bltm (make-instance 'biker-listening-to-music)))
        (format t "~%~A" biker)
        (format t "~%~A" bltm)
        (join-band biker)
        (format t "~%~A" biker)))

The output I get from the above is this:

    DYNAMIX> (print-object-test)
    #<BIKER needs to rock a little harder! {10043AF303}>
    #<BIKER-LISTENING-TO-MUSIC is rocking hard! {10043FAA63}>
    #<MIXIN-OBJECT (MUSIC-MIXIN BIKER) {10043AF303}>

Hopefully the above helps illustrate my question.  Any suggestions would be appreciated.

**Comment by rpav** [comment]
Sorry for the delay and I see you have a PR; better would likely be to remove the `PRINT-OBJECT` specialization for `MIXIN-CLASS` as you say.

I never really used this and I'm not sure it was ever a great idea, but if this seems the most useful way to define it, go for it.  I'm not sure too many others are using it. ;)

**Comment by elliottjohnson** [comment]
I've pushed a commit to remove the print-object method.  Should be good to go if you're interested in the pull request.  I do agree that this library seems like the approach I'd take.  Gary King has dynamic-classes that would fit the bill too, but I prefer yours.  Thanks again.
